# Generated by Django 6.1 on 2026-08-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('ASIGNADA', 'Asignada'), ('ACTUALIZADO', 'Actualizado'), ('PERSISTE', 'Persiste'), ('CLARIFICATION', 'Clarification'), ('CORREGIDA', 'Corregida')], default='UNASSIGNED', max_length=20),
        ),
    ]
