# Generated by Django 6.1 on 2026-08-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0002_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('SIN_ASIGNAR', 'Unassigned'), ('ASIGNADA', 'Asignada'), ('ACTUALIZADO', 'Actualizado'), ('PERSISTE', 'Persiste'), ('CLARIFICATION', 'Clarification'), ('CORREGIDA', 'Corregida')], default='SIN_ASIGNAR', max_length=20),
        ),
    ]
