# Generated by Django 6.1 on 2026-08-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0006_comment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(blank=True, choices=[('DEVELOPER', 'Developer'), ('QA', 'QA'), ('REQUESTER', 'Requester')], max_length=20, null=True),
        ),
    ]
